apiVersion: v1
kind: Service
metadata:
  labels:
    app: mynginx
  name: mynginx
  namespace: dev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
